<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Default.aspx.cs" Inherits="TuProyecto.Default" %>

<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Gestión de Plantas</title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <h2>Categorías de Plantas</h2>
            <asp:GridView ID="GridViewCategorias" runat="server" AutoGenerateColumns="false" DataKeyNames="IdCategoria"
                DataSourceID="SqlDataSourceCategorias" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                <Columns>
                    <asp:BoundField DataField="IdCategoria" HeaderText="ID" ReadOnly="true" />
                    <asp:BoundField DataField="NombreCategoria" HeaderText="Nombre" />
                    <asp:BoundField DataField="Descripcion" HeaderText="Descripción" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSourceCategorias" runat="server"
                ConnectionString="<%$ ConnectionStrings:GestionPlantasDBConnectionString %>"
                SelectCommand="SELECT * FROM Categorias"
                UpdateCommand="UPDATE Categorias SET NombreCategoria=@NombreCategoria, Descripcion=@Descripcion WHERE IdCategoria=@IdCategoria"
                DeleteCommand="DELETE FROM Categorias WHERE IdCategoria=@IdCategoria"
                InsertCommand="INSERT INTO Categorias (NombreCategoria, Descripcion) VALUES (@NombreCategoria, @Descripcion)">
                <UpdateParameters>
                    <asp:Parameter Name="NombreCategoria" Type="String" />
                    <asp:Parameter Name="Descripcion" Type="String" />
                    <asp:Parameter Name="IdCategoria" Type="Int32" />
                </UpdateParameters>
                <DeleteParameters>
                    <asp:Parameter Name="IdCategoria" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="NombreCategoria" Type="String" />
                    <asp:Parameter Name="Descripcion" Type="String" />
                </InsertParameters>
            </asp:SqlDataSource>

            <h2>Plantas</h2>
            <asp:GridView ID="GridViewPlantas" runat="server" AutoGenerateColumns="false" DataKeyNames="IdPlanta"
                DataSourceID="SqlDataSourcePlantas" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                <Columns>
                    <asp:BoundField DataField="IdPlanta" HeaderText="ID" ReadOnly="true" />
                    <asp:BoundField DataField="NombrePlanta" HeaderText="Nombre" />
                    <asp:BoundField DataField="Descripcion" HeaderText="Descripción" />
                    <asp:DropDownList ID="ddlCategoria" runat="server" SelectedValue='<%# Bind("IdCategoria") %>'>
                        <asp:ListItem Text="Seleccione Categoría" Value="" />
                    </asp:DropDownList>
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSourcePlantas" runat="server"
                ConnectionString="<%$ ConnectionStrings:GestionPlantasDBConnectionString %>"
                SelectCommand="SELECT IdPlanta, NombrePlanta, Descripcion, IdCategoria FROM Plantas"
                UpdateCommand="UPDATE Plantas SET NombrePlanta=@NombrePlanta, Descripcion=@Descripcion, IdCategoria=@IdCategoria WHERE IdPlanta=@IdPlanta"
                DeleteCommand="DELETE FROM Plantas WHERE IdPlanta=@IdPlanta"
                InsertCommand="INSERT INTO Plantas (NombrePlanta, Descripcion, IdCategoria) VALUES (@NombrePlanta, @Descripcion, @IdCategoria)">
                <UpdateParameters>
                    <asp:Parameter Name="NombrePlanta" Type="String" />
                    <asp:Parameter Name="Descripcion" Type="String" />
                    <asp:Parameter Name="IdCategoria" Type="Int32" />
                    <asp:Parameter Name="IdPlanta" Type="Int32" />
                </UpdateParameters>
                <DeleteParameters>
                    <asp:Parameter Name="IdPlanta" Type="Int32" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="NombrePlanta" Type="String" />
                    <asp:Parameter Name="Descripcion" Type="String" />
                    <asp:Parameter Name="IdCategoria" Type="Int32" />
                </InsertParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
